### ISSUE TITLE
File name format

### ISSUE THREAD

**Issue by vlad-ignatov** [smart-on-fhir/fhir-bulk-data-docs#5]
Currently we have some example file names like `0001.Patient.ndjson`. It is probably worth documenting the file name format better.  Possible questions are:

1. The number prefix is designed to control how the client OS sorts the files. Does it have to be placed before the resource type (eq. `0001.Patient.ndjson`), or after it (`Patient.0001.ndjson`)?s
Also, do these numbers really need to be prefixed with zeroes and if so, to what length?

2. The resourceType portion - should it be capitalized to match the FHIR conventions or lowercased to improve cross-OS compatibility?

**Comment by jmandel** [comment]
I think we want to be prescriptive here, so this is a great point to raise, @vlad-ignatov. 

My take would be to say: each link URL has an optional prefix leading up to `{optional prefix ending in dot}{mandatory resourceType}.ndjson`, where `{resourceType}` stands in for a resource type that's capitalized according to the FHIR specification. The prefix can be anything that ends in `.`.

I'd like to specify this (or something similarly prescriptive) so that clients can know unambiguously which files to inspect in order to find resources of a given type.

**Comment by gotdan** [comment]
Moved file types to explicit fields in json payload in v0.1, so specific file name format is no longer required
