### ISSUE TITLE
Comments on authorization.md

### ISSUE THREAD

**Issue by aviars** [smart-on-fhir/fhir-bulk-data-docs#56]
- Should the "JWKS URL (preferred)" URL be specified at a `.well-known` URL? 
- Perhaps the recommended token expire  time should be 10 minutes? 10 sees a little more common and provides a bit more leeway if system clocks are a little off.

**Comment by jmandel** [comment]
Thanks for these comments! (No big deal in this case, but in general if you're going to share more than one piece of feedback it would be a big help if you could create separate issues so that we can discuss and resolve each one independently.)

Would the `. well-known` path segment be relative to some predictable base? In this context I'm not sure I see how that could work, so I'm not sure what the advantage would be.

Regarding expiration times, could you include references to other services that choose 10 minutes over 5? My experience has been that keeping clocks synchronized within 5 minutes is no great challenge assuming you make any attempt to keep your clock synchronized at all.

**Comment by aviars** [comment]
I'll split things up next time.  The 10 minutes came from the suggested length of an authorization code in OAuth2. This is not that. I conflated the two. 5 minutes should not be an issue.

After further examination, I withdraw my suggestion of a `.well-known` URL in this context. Chalk it up to me not understanding the flow end-to-end.

I'm closing this issue.
